// /src/vuex/content/mutation-types.js
export const C_SET_CLEAN_SELECTIDS = 'U_SET_CLEAN_SELECTIDS'

export const C_SET_LIST_INIT = 'C_SET_LIST_INIT'
export const C_SET_PAGE = 'C_SET_PAGE'
export const C_SET_ALL_CONTENTS = 'C_SET_ALL_CONTENTS'
export const C_SET_RESULT = 'C_SET_RESULT'
export const C_SET_CONTENTS = 'C_SET_CONTENTS'
export const C_SET_PREVIEW_CONTENT = 'C_SET_PREVIEW_CONTENT'
export const C_SYNC_PREVIEW_CONTENT_DATA = 'C_SYNC_PREVIEW_CONTENT_DATA'

// 视图切换
export const C_SET_DETAIL = 'C_SET_DETAIL'
export const C_SET_VIEW = 'C_SET_VIEW'
export const C_SET_PREVIEW = 'C_SET_PREVIEW'
export const C_SET_QUEUE = 'C_SET_QUEUE'
export const C_SET_LEAVE = 'C_SET_LEAVE'
// 过滤器
export const C_SET_CREATOR = 'C_SET_CREATOR'
export const C_SET_PERIOD = 'C_SET_PERIOD'
export const C_SET_TYPE = 'C_SET_TYPE'

// 排序
export const C_SET_SORT = 'C_SET_SORT'
export const C_SELECT_ALL = 'C_SELECT_ALL'
export const C_SELECTED = 'C_SELECTED'
export const C_SELECT_SYNC_DATA = 'C_SELECT_SYNC_DATA'
export const C_SELECT_INIT_DATA = 'C_SELECT_INIT_DATA'
export const C_SELECT_CLEAR_DATA = 'C_SELECT_CLEAR_DATA'
export const C_SELECTED_ID = 'C_SELECTED_ID'


// 模态框
export const C_SET_DETELE_CONTENT_MODAL = 'C_SET_DETELE_CONTENT_MODAL'
export const C_SET_ADD_CONTENT_MODAL = 'C_SET_ADD_CONTENT_MODAL'
export const C_SET_LEAVE_CONTENT_MODAL = 'C_SET_LEAVE_CONTENT_MODAL'

//推送
export const C_SET_MODAL_INIT = 'C_SET_MODAL_INIT'
export const C_SET_MODAL_RESULT = 'C_SET_MODAL_RESULT'
export const C_SET_MODAL_CONTENTS = 'C_SET_MODAL_CONTENTS'
export const C_SET_MODAL_PAGE = 'C_SET_MODAL_PAGE'
export const C_SET_MODAL_CREATOR = 'C_SET_MODAL_CREATOR'
export const C_SET_MODAL_PERIOD = 'C_SET_MODAL_PERIOD'
export const C_SET_MODAL_TYPE = 'C_SET_MODAL_TYPE'

export const C_SET_MODAL_SORT = 'C_SET_MODAL_SORT'
export const C_SET_MODAL_SELECTED = 'C_SET_MODAL_SELECTED'
export const C_SET_MODAL_SELECTEDIDS = 'C_SET_MODAL_SELECTEDIDS'
export const C_SET_MODAL_SELECT_INIT_DATA = 'C_SET_MODAL_SELECT_INIT_DATA'
export const C_SET_REMOVE_MODAL_SELECTEDIDS = 'C_SET_REMOVE_MODAL_SELECTEDIDS'
export const C_SHOW_DETAIL_SYNC_DATA = 'C_SHOW_DETAIL_SYNC_DATA'

export const C_SET_CONTENT_ONE = 'C_SET_CONTENT_ONE'