// /src/vuex/app/mutation-types.js
export const A_SET_CLEAN_SELECTIDS = 'A_SET_CLEAN_SELECTIDS'

export const A_SET_DETAIL_LEVEL = 'A_SET_DETAIL_LEVEL'
export const A_SET_LIST_INIT = 'A_SET_LIST_INIT'
export const A_SET_PAGE = 'A_SET_PAGE'
export const A_SET_RESULT = 'A_SET_RESULT'
export const A_SET_APPS = 'A_SET_APPS'

export const A_SET_DETAIL = 'A_SET_DETAIL'
  // 过滤器
export const A_SET_CREATOR = 'A_SET_CREATOR'
export const A_SET_PERIOD = 'A_SET_PERIOD'
export const A_SET_TYPE = 'A_SET_TYPE'

// 排序
export const A_SET_SORT = 'A_SET_SORT'

export const A_SET_PLAY_MODE = 'A_SET_PLAY_MODE'
export const A_SET_SWITCH_MODE = 'A_SET_SWITCH_MODE'

// 模态框
export const A_SET_ADD_APP_MODAL = 'A_SET_ADD_APP_MODAL'
export const A_SET_DETELE_APP_MODAL = 'A_SET_DETELE_APP_MODAL'

// 发布模态框
export const A_SET_ADD_PUBLISHED_MODAL = 'A_SET_ADD_PUBLISHED_MODAL'
export const A_SET_ADD_CANCEL_MODAL = 'A_SET_ADD_CANCEL_MODAL'

export const A_SET_MODAL_PAGE = 'A_SET_MODAL_PAGE'
export const A_SET_MODAL_CREATOR = 'A_SET_MODAL_CREATOR'
export const A_SET_MODAL_PERIOD = 'A_SET_MODAL_PERIOD'
export const A_SET_MODAL_LOCATION = 'A_SET_MODAL_LOCATION'
export const A_SET_MODAL_SORT = 'A_SET_MODAL_SORT'
export const A_SET_MODAL_RESULT = 'A_SET_MODAL_RESULT'
export const A_SET_MODAL_SCREENS = 'A_SET_MODAL_SCREENS'
export const A_SET_MODAL_SELECTEDIDS = 'A_SET_MODAL_SELECTEDIDS'
export const A_SET_MODAL_SELECT_INIT_DATA = 'A_SET_MODAL_SELECT_INIT_DATA'
export const A_SET_MODAL_SELECT_SYNC_DATA = 'A_SET_MODAL_SELECT_SYNC_DATA'
export const A_SET_MODAL_SELECTED = 'A_SET_MODAL_SELECTED'
export const A_SET_MODAL_SELECT_ALL = 'A_SET_MODAL_SELECT_ALL'
export const A_CHANGE_MODAL_SELECTEDID = 'A_CHANGE_MODAL_SELECTEDID'

export const A_SELECT_ALL = 'A_SELECT_ALL'
export const A_SELECTED = 'A_SELECTED'
export const A_SELECT_SYNC_DATA = 'A_SELECT_SYNC_DATA'
export const A_SELECT_INIT_DATA = 'A_SELECT_INIT_DATA'
export const A_SELECT_CLEAR_DATA = 'A_SELECT_CLEAR_DATA'
export const A_SELECTED_ID = 'A_SELECTED_ID'

export const A_SHOW_DETAIL_SYNC_DATA = 'A_SHOW_DETAIL_SYNC_DATA'

// // 签到
// export const A_SET_SIGN_RESULT = 'A_SET_SIGN_RESULT'
// export const A_SET_SIGN_SIGNS = 'A_SET_SIGN_SIGNS'
// export const A_SET_SIGN_PAGE = 'A_SET_SIGN_PAGE'
// export const A_SET_SIGN_SELECT_INIT_DATA = 'A_SET_SIGN_SELECT_INIT_DATA'
// export const A_SET_SIGN_SELECT_SYNC_DATA = 'A_SET_SIGN_SELECT_SYNC_DATA'
// export const A_SET_SIGN_SELECTED = 'A_SET_SIGN_SELECTED'
// export const A_SET_SIGN_SELECTEDIDS = 'A_SET_SIGN_SELECTEDIDS'
// export const A_SET_SIGN_SELECT_ALL = 'A_SET_SIGN_SELECT_ALL'


//照片墙审核
export const A_SET_CHECK = 'A_SET_CHECK'
export const A_SET_PENGING_lIST = 'A_SET_PENGING_lIST'
export const A_REMOVE_PENGING_lIST = 'A_REMOVE_PENGING_lIST'
export const A_CHANGE_PENGING_lIST = 'A_CHANGE_PENGING_lIST'
export const A_CHECK_PENDING_COUNT = 'A_CHECK_PENDING_COUNT'
export const A_SET_ADD_CHECK_MODAL = 'A_SET_ADD_CHECK_MODAL'

// 微信用户管理
export const A_SET_WECHAT_SORT = 'A_SET_WECHAT_SORT'
export const A_SET_WECHAT_PAGE = 'A_SET_WECHAT_PAGE'
export const A_SET_WECHAT_RESULT = 'A_SET_WECHAT_RESULT'
export const A_SET_WECHAT_USERS = 'A_SET_WECHAT_USERS'
export const A_SET_WECHAT_SELECT_INIT_DATA = 'A_SET_WECHAT_SELECT_INIT_DATA'
export const A_SET_WECHAT_SELECT_SYNC_DATA = 'A_SET_WECHAT_SELECT_SYNC_DATA'
export const A_SET_WECHAT_SELECTED = 'A_SET_WECHAT_SELECTED'
export const A_SET_WECHAT_SELECTEDIDS = 'A_SET_WECHAT_SELECTEDIDS'
export const A_SET_WECHAT_SELECT_ALL = 'A_SET_WECHAT_SELECT_ALL'
export const A_SET_DETELE_WECHAT_MODAL = 'A_SET_DETELE_WECHAT_MODAL'
export const A_SET_CLEAN_WECHAT_SELECTEDIDS = 'A_SET_CLEAN_WECHAT_SELECTEDIDS'

// mobile 
export const A_SET_APP_ONE = 'A_SET_APP_ONE'